language: python
python:
  - "3.6"
  - "3.5"
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - pycodestyle ergoFACE
  - pytest --verbose --capture=no ergoFACE
  - pip install .
sudo: false
