sudo: false

language:
  - python

python:
  - 2.7


install:
  - pip install -r requirements.txt

script:
  - pycodestyle ergoFACE
  - pytest --verbose --capture=no ergoFACE
  - pip install .

notifications:
  email: false
